replicaCount: 1

image:
  repository: t2e
  tag: "d1712812565f53967aa4e81589d01f5ab49534a0"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"