replicaCount: 1

image:
  repository: t2e
  tag: "a582172011a247ef1c3780cf569fb88a3d71bb03"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"